import pytest

from day08 import collect_antennae, calculate_antinodes

@pytest.fixture
def aoc():
    return '''............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............'''.split('\n')


def test_collect_antennae(aoc):
    assert collect_antennae(aoc)['0'][0] == (1, 8)
    assert collect_antennae(aoc)['A'][-1] == (9, 9)


def test_calculate_antinodes(aoc):
    antennae = collect_antennae(aoc)
    assert len(set(calculate_antinodes(antennae, aoc))) == 14

